### ISSUE TITLE
v3.3.0 problemas con CancelOrderObserver

### ISSUE THREAD

**Issue by jotamolas** [mobbexco/magento-2#146]
Buenas tardes, al momento de cancelar una Orden, veo esto en los logs.
```bash
Notice: Undefined index: order_id in /var/www/html/magento/vendor/mobbexco/magento-2/Observer/CancelOrderObserver.php
```

**Comment by jlmobbex** [comment]
Buen día @jotamolas! Gracias por tus comentarios, ya tenemos visto el error (#147) y está planificado para quedar corregido en la próxima versión del módulo.

**Comment by jlmobbex** [comment]
#150
