### ISSUE TITLE
Table 'xxx.mobbex_log' doesn't exist

### ISSUE THREAD

**Issue by michaeldyl520** [mobbexco/magento-2#152]
Verson 3.4.0
Can you fix it?

**Comment by jlmobbex** [comment]
Hola @michaeldyl520! Gracias por tus comentarios. Te comento que el bug que mencionás lo tenemos visto y está planificado para quedar corregido en la próxima versión del plugin.

**Comment by jlmobbex** [comment]
El error quedó resuelto en la última versión publicada (#153 y #155).
