### ISSUE TITLE
Incompatibilidad con PHP 8.2

### ISSUE THREAD

**Issue by manuelcanepa** [mobbexco/magento-2#171]
Al instalar el modulo sobre PHP 8.2 se presentan multiples problemas criticos de creación dinámica de propiedades, principalmente al usar el "instanciador". La información técnica puede verse en la [página oficial de php](https://www.php.net/manual/en/language.oop5.properties.php#language.oop5.properties.dynamic-properties)

Podría usarse la etiqueta #[AllowDynamicProperties] pero lo ideal sería usar las buenas prácticas de Magento y declarar de forma explícita la dependencia, por ejemplo, para el caso de la clase Mobbex\Webpay\Helper\Sdk, el constructor pasaría de:

```
    public function __construct(
        \Mobbex\Webpay\Helper\Instantiator $instantiator,
        \Magento\Framework\Module\ResourceInterface $moduleResource,
        \Magento\Framework\App\ProductMetadataInterface $productMetadata,
        \Mobbex\Webpay\Model\Cache $cache
    ) {
        $instantiator->setProperties($this, ['config', 'helper', '_urlBuilder', 'logger']);
        $this->moduleResource  = $moduleResource;
        $this->productMetadata = $productMetadata;
        $this->cache           = $cache;
    }
```

A esto:

```   
    public function __construct(
        \Mobbex\Webpay\Helper\Config $config,
        \Mobbex\Webpay\Helper\Mobbex $helper,
        \Magento\Framework\UrlInterface $_urlBuilder,
        \Mobbex\Webpay\Helper\Logger $logger,
        \Magento\Framework\Module\ResourceInterface $moduleResource,
        \Magento\Framework\App\ProductMetadataInterface $productMetadata,
        \Mobbex\Webpay\Model\Cache $cache
    ) {
        $this->config          = $config;
        $this->helper          = $helper;
        $this->_urlBuilder     = $_urlBuilder;
        $this->logger          = $logger;
        $this->moduleResource  = $moduleResource;
        $this->productMetadata = $productMetadata;
        $this->cache           = $cache;
    }
```

**Comment by jlmobbex** [comment]
Hola @manuelcanepa! Gracias por tus comentarios, estamos evaluando distintas opciones para integrar estos requisitos en el módulo. Por ahora, comento que el mensaje que muestra PHP es de deprecado y no debería parar la ejecución del código. Apenas tengamos novedades te vamos a estar avisando!

**Comment by manuelcanepa** [comment]
> Hola @manuelcanepa! Gracias por tus comentarios, estamos evaluando distintas opciones para integrar estos requisitos en el módulo. Por ahora, comento que el mensaje que muestra PHP es de deprecado y no debería parar la ejecución del código. Apenas tengamos novedades te vamos a estar avisando!

En PHP 8.1 muestra un mensaje (cosa que no genera demasiado inconveniente) pero en 8.2 si que se detiene la ejecucion porque genera una excepcion. De todas formas, gracias por la respuesta.
