### ISSUE TITLE
Agregar versión del módulo en el Backend

### ISSUE THREAD

**Issue by fedlerner** [mobbexco/magento-2#24]
Me parece útil agregar la versión del módulo que uno tiene instalado en el backend de Magento. 
De esta forma, uno podría visualizar rápidamente la versión instalada y compararla con las versiones disponibles del repositorio, para saber que cambios/fixes están faltando.

A mi me surgió esta necesidad ya que trabajo con una empresa terciarizada, y no tengo una visibilidad fácil de dicha información. Y necesito estar al tanto de donde estamos parados y si necesitamos hacer un upgrade de versión.

Ejemplo de lo que estoy hablando: 
![image](https://user-images.githubusercontent.com/8109433/105528638-fdb7ee80-5cc3-11eb-870f-4f2af0cb3482.png)

**Comment by jlmobbex** [comment]
#35 Hola @fedlerner! Te informamos que esta característica fue agregada al código y estará disponible en la próxima versión. Gracias por tu comentario!
