### ISSUE TITLE
Habilitar opción de Refund (Credit Memo) Parcial

### ISSUE THREAD

**Issue by fedlerner** [mobbexco/magento-2#32]
Buenas!

Al parecer el módulo tiene deshabilitada la opción de realizar un "refund parcial" de una orden, por lo que no es posible si por ejemplo uno no tiene stock de ciertos productos, hacer una devolución de solamente dichos productos. 

Por lo que estuve investigando, _**puede ser**_ un flag que se debe setear en true:
protected $_canRefundInvoicePartial = true;
https://magento.stackexchange.com/questions/53720/partial-refund-option-missing-qty-to-refund

Así es como se visualiza la pantalla de Credit Memo en un orden abonada con un método de pago que permite partial refund: 
![image](https://user-images.githubusercontent.com/8109433/105919378-4d741e00-6014-11eb-9855-588a10f3c5cb.png)

Así es como se visualiza en una orden abonada con Mobbex:
![image](https://user-images.githubusercontent.com/8109433/105919418-6381de80-6014-11eb-817b-83ea1296e272.png)

Como se puede ver, en el caso de una orden abonada con Mobbex, automáticamente te llena el campo de "Qty to Refund" y no te da opción de cambiarlo y hacer un refund parcial.

Saludos!

**Comment by jlmobbex** [comment]
Hola @fedlerner! Actualmente ambas flags están integradas en el código (1.2.0 en adelante), pero estamos investigando el error por si nos falta otra configuración o método para que funcione. Como siempre, muchas gracias por tus comentarios!

**Comment by jlmobbex** [comment]
@fedlerner Te comento que no pudimos reproducir el problema de nuestro lado. En caso de que siga sin funcionar te recomiendo actualizar tanto Magento como el plugin a sus últimas versiones.
