### ISSUE TITLE
El widget de info financiera en la página del producto no tiene en cuenta si el producto tiene planes Ahora desactivados

### ISSUE THREAD

**Issue by nmarquev** [mobbexco/magento-2#50]
El widget modal de info financiera en la página del producto no tiene en cuenta si el producto tiene planes Ahora desactivados. Si lo tiene en cuenta al momento del checkout, cuando abre el formulario de pago Mobbex, alli no aparecen los planes Ahora (eso está bien) pero en el widget informativo, muestra todos los planes Ahora aunque el producto los tenga deshabilitado

**Comment by jlmobbex** [comment]
@nmarquev Gracias por tus comentarios! Ya estamos trabajando para que esta función se encuentre disponible en la próxima versión.
