### ISSUE TITLE
Mail de Confirmacion y cambio en la pagina de retorno

### ISSUE THREAD

**Issue by TomasFleitas** [mobbexco/magento-2#6]
Buenas tardes, estoy integrando Mobbex en Magento 2.3.5-p1 y me esta pasando que el correo de confirmacion que envia Magento se esta enviando cuando se levanta el PopUp de Mobbox y no al finalizar el proceso de pago (ya sea con cupon o con tarjeta).

Quiero aclarar que para que se envie el correo cambie el argumento de este metodo de **false** -> **true**
![image](https://user-images.githubusercontent.com/32066217/97440454-3f740b80-1906-11eb-9d8f-9ddd7246e62e.png)

* hay alguna manera de solucionar esto ?

y ya que estoy dejo una modificacion que hice en el codigo que me estaba generando problemas cuando Mobbex retornaba a Magento
![image](https://user-images.githubusercontent.com/32066217/97440784-adb8ce00-1906-11eb-92cc-3bcc5e25f3a2.png)

* la url **webpay/payment/paymentreturn** generaba que me quede la pagina en blanco, entonces cree una pagina nueva con la url **success**.

**Comment by mobbexdev** [comment]
@TomasFleitas muchas gracias por el comentario! Lo vamos a revisar a estar revisando en la nueva versión que saldrá en los próximos dias!

**Comment by jlmobbex** [comment]
Estas configuraciones y correcciones fueron añadidas en la versión 1.2.0 #19
