### ISSUE TITLE
Habilitar módulo en Packagist.org

### ISSUE THREAD

**Issue by barbazul** [mobbexco/magento-2#8]
El módulo no está disponible en packagist.org y tampoco se podría instalar por composer porque está mal estructurado el repositorio.

https://packagist.org/?query=mobbex%2Fmodule-webpay

https://devdocs.magento.com/guides/v2.4/extension-dev-guide/package/package_module.html

**Comment by jlmobbex** [comment]
Hola @barbazul, gracias por tus comentarios! Ya estamos trabajando en la estructura del modulo para que pronto se pueda instalar por composer, y apenas tengamos eso listo lo publicaremos en packagist.
