### ISSUE TITLE
Datos de financiación en página de productos no toma el precio especial

### ISSUE THREAD

**Issue by ululaecommerce** [mobbexco/magento-2#93]
Hola!

Cuando un producto tiene precio especial, la información que toma para mostrar los planes de financiación toma el full price, por lo que queda confuso para el cliente.

Adjunto 2 imágenes donde se puede ver.

Saludos!

![foto2 jpg](https://user-images.githubusercontent.com/83651110/162769476-6b8ff537-e8dc-4042-8eb4-504f82e5566c.png)

![Foto1 jpg](https://user-images.githubusercontent.com/83651110/162769462-d7280409-f1b4-4c6f-bb01-a3a3338893cf.png)

**Comment by jlmobbex** [comment]
Hola @ululaecommerce, muchas gracias por tus comentarios! Pudimos reproducir el problema de nuestro lado y estamos trabajando en una solución. Lo más probable es que esta quede publicada en la próxima versión del módulo, te mantendremos al tanto por este medio.
