### ISSUE TITLE
Columna no existente

### ISSUE THREAD

**Issue by morgothx** [mobbexco/magento-2#96]
mobbex_customfield' doesn't exist, query was: SELECT `main_table`.* FROM `mobbex_customfield` AS `main_table` WHERE (`row_id` = '1') AND (`object` = 'product') AND (`field_name` = 'is_subscription')

Este error sale al ingresar a la edicion de un producto desde el administrador de magento.

Se corrieron los comandos:

composer require mobbexco/magento-2
php bin/magento module:enable Mobbex_Webpay
php bin/magento setup:upgrade
php bin/magento setup:static-content:deploy -f

El error salio y luego se corrio

composer update mobbexco/magento-2
php bin/magento setup:upgrade
php bin/magento setup:static-content:deploy -f

Pero el error persiste.

En el composer.json veo

"mobbexco/magento-2": "^3.0",  (Creo que la version que quedo es 3.1)

y la version de magento es 2.4.3-p2

Tambien se intento borrar cache y correr reindex sin resultado

y si se puede ver el metodo de pago en la configuracion del administrador

**Comment by jlmobbex** [comment]
Hola @morgothx, gracias por el comentario! Pudimos replicar el error y estamos trabajando en una solución. Probablemente quede publicada en la próxima versión del módulo, aunque te voy avisando por este medio.

**Comment by morgothx** [comment]
Muchas gracias, ya lo he probado y pude ingresar a la edicion de productos
