### ISSUE TITLE
Problema en Magento 2.4.4 y PHP 8.1

### ISSUE THREAD

**Issue by SoyLinux** [mobbexco/magento-2#99]
Hola, estoy teniendo problemas para instalar esta extensión en Magneto 2.4.4 y PHP 8.1.
Adjunto captura.

![errorMobbexMagento2](https://user-images.githubusercontent.com/44839521/170247495-3857150f-02c9-4b7d-af2c-fb783c9bb0e3.png)

Gracias!

**Comment by jlmobbex** [comment]
Hola @SoyLinux! Pudimos reproducir el problema y ya tenemos lista una corrección (f3ea368ff0613d5ed73609a122d8b5515912817e) que quedará publicada hoy en la versión 3.0.3 del plugin. Muchas gracias por tus comentarios!
